url: https://DeustoKom.github.io
baseurl: /RatosConDatos

# Site settings
title: Ratos con Datos
email: deustokom@deusto.es
description: "El reto de visualizar datos COVID-19 durante la pandemia. Organizado por DeustoKom."


# Team names, titles and social links
people:
- name: Pablo Rey
  pic: pablo-rey
  position: Numeroteca
  social:
    - title: twitter
      url: https://twitter.com/numeroteca
    - title: link
      url: http://numeroteca.org/
    - title: google-plus
      url: #
- name: Mikel Madina
  pic: mikel-madina
  position: Visualización de datos
  social:
    - title: twitter
      url: https://twitter.com/mikelmadina
    - title: facebook
      url: #
    - title: stack-overflow
      url: #
- name: Miren berasategi
  pic: miren-berasategi
  position: Universidad de Deusto
  social:
    - title: twitter
      url: mberasategi
    - title: link
      url: https://miren.bz
    - title: github
      url: https://github.com/mberasategi

- name: Asier Murciego
  pic: asier-murciego
  position: Orkestra
  social:
    - title: twitter
      url: https://twitter.com/murciego
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/deustokomunika
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket 
#    url: http://bitbucket.org/jekyll
  - title: youtube
    url: 
  - title: github
    url: http://github.com/deustokom/

# Postal address (add as many lines as necessary)
address:
  - line: Mundaiz 50
  - line: 20012 Donostia

# Build settings
markdown: kramdown